<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>CA1822</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="twoevents.xel" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="RegSrvrTest.xml" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="..\Server\Bubbles.XEvent.MCPServer.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.Data.SqlClient.Extensions.Azure" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.SqlServer.SqlManagementObjects" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>
</Project>